# Generated by Django 6.0.7 on 2026-07-24 15:08

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('enrollment_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GradeConversionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score_10', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('max_score_10', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('letter_grade', models.CharField(max_length=5)),
                ('score_4', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('classification', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('STUDENTS', 'Sinh viên'), ('SCORES', 'Điểm số'), ('SCHEDULES', 'Thời khóa biểu'), ('FACULTIES', 'Khoa/Ngành')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('PARTIAL_SUCCESS', 'Thành công một phần'), ('FAILED', 'Thất bại')], max_length=20)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('max_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('STUDENT', 'Sinh viên'), ('ADMIN', 'Quản trị viên'), ('ORGOFFICER', 'Cán bộ Tổ chức'), ('LECTURER', 'Giảng viên')], default='STUDENT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang giải quyết'), ('CLOSED', 'Đã đóng')], default='PENDING', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('target_audiences', models.JSONField(blank=True, null=True)),
                ('max_participants', models.IntegerField()),
                ('waiting_list_capacity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('is_youth_union', models.BooleanField(default=False)),
                ('training_points', models.IntegerField(default=0)),
                ('app_route', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_code', models.CharField(db_index=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh báo cáo')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('IN_PROGRESS', 'Đang sửa chữa'), ('RESOLVED', 'Đã khắc phục')], default='PENDING', max_length=20)),
                ('resolution_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh sau khắc phục')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_facility_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_type', models.CharField(choices=[('TUITION', 'Học phí'), ('CLUB_FUND', 'Quỹ CLB'), ('YOUTH_UNION_FEE', 'Đoàn phí')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='stsv_app.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_enrollment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stsv_app.lecturerprofile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='stsv_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='HomeroomClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_classes', to='stsv_app.cohort')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_classes', to='stsv_app.lecturerprofile')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_classes', to='stsv_app.major')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('REMINDER', 'Nhắc nhở'), ('ALERT', 'Cảnh báo'), ('GENERAL', 'Thông báo chung'), ('EVENT', 'Sự kiện')], default='GENERAL', max_length=20)),
                ('related_link', models.CharField(blank=True, max_length=255, null=True)),
                ('action_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('FACULTY', 'Cấp Khoa'), ('YOUTH_UNION_ASSOC', 'Đoàn - Hội'), ('CLUB', 'Câu lạc bộ')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('SUSPENDED', 'Đình chỉ')], default='ACTIVE', max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stsv_app.lecturerprofile')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stsv_app.faculty')),
                ('parent_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stsv_app.orgprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLASS', 'Học trên lớp'), ('EXAM', 'Lịch thi')], default='CLASS', max_length=20)),
                ('day_of_week', models.IntegerField()),
                ('exact_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('is_makeup_class', models.BooleanField(default=False)),
                ('sync_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.courseclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('is_youth_union_linked', models.BooleanField(default=False)),
                ('youth_union_token', models.CharField(blank=True, max_length=500, null=True)),
                ('last_sync_youth_union', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='stsv_app.cohort')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='stsv_app.faculty')),
                ('homeroom_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='stsv_app.homeroomclass')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='stsv_app.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score_10', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_score_4', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_score_letter', models.CharField(blank=True, max_length=5, null=True)),
                ('is_passed', models.BooleanField(blank=True, db_index=True, null=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ENROLLMENT_CERT', 'Giấy xác nhận sinh viên'), ('TRANSCRIPT', 'Bảng điểm'), ('LEAVE_OF_ABSENCE', 'Đơn xin tạm nghỉ học')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang xử lý'), ('READY_FOR_PICKUP', 'Đã có kết quả'), ('DONE', 'Đã hoàn thành'), ('REJECTED', 'Từ chối')], db_index=True, default='PENDING', max_length=20)),
                ('attached_files', models.JSONField(blank=True, null=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='service_responses/')),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], db_index=True, default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('VNPAY', 'VNPay'), ('MOMO', 'MoMo'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('refund_status', models.CharField(choices=[('NONE', 'Không'), ('REQUESTED', 'Yêu cầu hoàn tiền'), ('REFUNDED', 'Đã hoàn tiền')], default='NONE', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.fee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='homeroomclass',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presided_classes', to='stsv_app.studentprofile'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Đã đăng ký'), ('WAITLIST', 'Danh sách chờ'), ('CANCELLED', 'Đã hủy')], default='REGISTERED', max_length=20)),
                ('queue_position', models.IntegerField(default=0)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('feedback_submitted', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('score_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.scorecomponent')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentcourse')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSemesterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã nộp'), ('CLASS_APPROVED', 'Lớp trưởng đã duyệt'), ('FACULTY_APPROVED', 'Khoa đã duyệt')], default='DRAFT', max_length=20)),
                ('total_student_score', models.IntegerField(default=0)),
                ('total_class_score', models.IntegerField(default=0)),
                ('total_final_score', models.IntegerField(default=0)),
                ('class_approved_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_approved_at', models.DateTimeField(blank=True, null=True)),
                ('class_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_approved_training_points', to=settings.AUTH_USER_MODEL)),
                ('faculty_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_approved_training_points', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_points', to='stsv_app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSemesterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_gpa_4', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester_earned_credits', models.IntegerField()),
                ('semester_training_points', models.IntegerField()),
                ('training_point_classification', models.CharField(max_length=50)),
                ('cumulative_gpa_4', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cumulative_earned_credits', models.IntegerField()),
                ('cumulative_training_points', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.faculty')),
                ('prerequisite_subjects', models.ManyToManyField(blank=True, to='stsv_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='scorecomponent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.subject'),
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_semester', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.cohort')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.major')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='courseclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.subject'),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterPointDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_score', models.IntegerField(default=0)),
                ('class_score', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('semester_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stsv_app.studentsemesterpoint')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.trainingcriterion')),
            ],
        ),
        migrations.CreateModel(
            name='PointProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('file_url', models.FileField(upload_to='point_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentprofile')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.trainingcriterion')),
            ],
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_changed', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stsv_app.event')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentprofile')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.trainingcriterion')),
            ],
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.trainingcriterion'),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('device_os', models.CharField(blank=True, choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10, null=True)),
                ('calendar_sync_token', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.notificationtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YouthUnionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Đã đồng bộ'), ('PENDING_SYNC', 'Chờ đồng bộ'), ('FAILED', 'Thất bại')], default='PENDING_SYNC', max_length=20)),
                ('sync_response', models.TextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stsv_app.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.studentprofile')),
            ],
        ),
    ]
