# Generated by Django 6.0.7 on 2026-09-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='criterion_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
