# Generated by Django 6.0.7 on 2026-08-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0002_checkinsession_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinsession',
            name='created_at',
        ),
    ]
