# Generated by Django 6.0.7 on 2026-09-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0002_eventcategory_criterion_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: Điều 1, Điều 2', max_length=255, unique=True)),
                ('max_points', models.IntegerField(default=20, help_text='Trần điểm tối đa cho Điều này')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stsv_app.trainingcriterion')),
            ],
        ),
    ]
