# Generated by Django 6.0.7 on 2026-08-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0003_remove_checkinsession_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
