# Generated by Django 6.0.7 on 2026-09-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0003_trainingcriterion_trainingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrule',
            name='criterion',
        ),
        migrations.DeleteModel(
            name='TrainingCriterion',
        ),
        migrations.DeleteModel(
            name='TrainingRule',
        ),
    ]
