# Generated by Django 6.0.7 on 2026-09-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0004_remove_trainingrule_criterion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: Điều 1, Điều 2', max_length=255, unique=True)),
                ('max_points', models.IntegerField(default=20, help_text='Trần điểm tối đa cho Điều này')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='criterion_name',
        ),
        migrations.RemoveField(
            model_name='pointtransaction',
            name='criterion_code',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stsv_app.trainingcriterion'),
        ),
        migrations.CreateModel(
            name='TrainingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã quy tắc, ví dụ: 199', max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='stsv_app.trainingcriterion')),
            ],
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stsv_app.trainingrule'),
        ),
    ]
