# Generated by Django 6.0.7 on 2026-08-20 11:11

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0004_delete_servicerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='pointproof',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='pointproof',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='pointproof',
            name='student',
        ),
        migrations.AddField(
            model_name='gradeconversionrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationsynclog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointproof',
            name='point_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='stsv_app.semesterpointdetail'),
        ),
        migrations.AddField(
            model_name='trainingcriterion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria', to='stsv_app.trainingcriterion'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('VNPAY', 'VNPay'), ('MOMO', 'MoMo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pointproof',
            name='file_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Minh chứng'),
        ),
    ]
