# Generated by Django 6.0.7 on 2026-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0005_trainingcriterion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentsemesterpoint',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='semester',
            name='is_evaluation_open',
            field=models.BooleanField(default=False, help_text='Mở đợt chấm điểm rèn luyện cho toàn trường'),
        ),
    ]
