# Generated by Django 6.0.7 on 2026-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0006_alter_pointtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsemesterpoint',
            name='class_points_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentsemesterpoint',
            name='faculty_points_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
