# Generated by Django 6.0.7 on 2026-09-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0007_studentsemesterpoint_class_points_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrule',
            name='is_proof_required',
            field=models.BooleanField(default=False),
        ),
    ]
