# Generated by Django 6.0.7 on 2026-09-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0008_trainingrule_is_proof_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrule',
            name='is_event_rule',
            field=models.BooleanField(default=False, help_text='Là quy tắc để lưu điểm cộng tự động từ sự kiện'),
        ),
    ]
