# Generated by Django 6.0.7 on 2026-09-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0010_trainingrulegroup_trainingrule_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrule',
            name='group',
        ),
        migrations.DeleteModel(
            name='TrainingRuleGroup',
        ),
    ]
