# Generated by Django 6.0.7 on 2026-09-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0011_remove_trainingrule_group_delete_trainingrulegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_single_choice', models.BooleanField(default=False)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='stsv_app.trainingcriterion')),
            ],
        ),
        migrations.AddField(
            model_name='trainingrule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='stsv_app.trainingrulegroup'),
        ),
    ]
