# Generated by Django 6.0.7 on 2026-09-07 15:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0012_trainingrulegroup_trainingrule_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecampaign',
            name='receiving_account_info',
        ),
        migrations.AddField(
            model_name='feecampaign',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Tên chủ tài khoản nhận (VD: NGUYEN VAN A)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='feecampaign',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Số tài khoản nhận tiền của Thủ quỹ/Lớp trưởng', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feecampaign',
            name='bank_name',
            field=models.CharField(blank=True, default='MBBank', help_text='Mã/Tên ngân hàng (VD: MBBank, VCB, Techcombank, TPBank, Vietinbank)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feecampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feecampaign',
            name='homeroom_class',
            field=models.ForeignKey(blank=True, help_text='Lớp áp dụng (để trống nếu áp dụng toàn trường/khoa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_campaigns', to='stsv_app.homeroomclass'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Ghi chú thêm hoặc lý do từ chối'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('VIETQR', 'Chuyển khoản VietQR'), ('BANK_TRANSFER_PROOF', 'Nộp ảnh minh chứng chuyển khoản'), ('CASH', 'Tiền mặt trực tiếp')], default='VIETQR', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feecampaign',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='feecampaign',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='feecampaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='feecampaign',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn chót'),
        ),
        migrations.AlterField(
            model_name='feecampaign',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='Bắt buộc'),
        ),
        migrations.AlterField(
            model_name='feecampaign',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên đợt thu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Ảnh biên lai / bill chuyển khoản', null=True, upload_to='finance/proofs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('SUCCESS', 'Đã hoàn thành'), ('FAILED', 'Thất bại'), ('REJECTED', 'Từ chối minh chứng')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Mã giao dịch hoặc mã tham chiếu', max_length=100),
        ),
    ]
