# Generated by Django 6.0.7 on 2026-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0013_remove_feecampaign_receiving_account_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='proof_image',
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Ghi chú thêm'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('VIETQR', 'Chuyển khoản VietQR'), ('CASH', 'Tiền mặt trực tiếp')], default='VIETQR', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('SUCCESS', 'Đã hoàn thành')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
