# Generated by Django 6.0.7 on 2026-09-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0014_remove_payment_proof_image_alter_payment_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='verified_by',
        ),
    ]
