# Generated by Django 6.0.7 on 2026-09-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsv_app', '0015_remove_payment_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecampaign',
            name='bank_name',
            field=models.CharField(choices=[('MBBank', 'MBBank - Ngân hàng Quân Đội'), ('VCB', 'Vietcombank - Ngân hàng Ngoại Thương'), ('Techcombank', 'Techcombank - Ngân hàng Kỹ Thương'), ('VietinBank', 'VietinBank - Ngân hàng Công Thương'), ('BIDV', 'BIDV - Đầu tư và Phát triển'), ('Agribank', 'Agribank - Nông nghiệp & PTNT'), ('ACB', 'ACB - Ngân hàng Á Châu'), ('TPBank', 'TPBank - Ngân hàng Tiên Phong'), ('VPBank', 'VPBank - Việt Nam Thịnh Vượng'), ('Sacombank', 'Sacombank - Sài Gòn Thương Tín'), ('HDBank', 'HDBank - Phát triển TP.HCM'), ('VIB', 'VIB - Ngân hàng Quốc Tế'), ('MSB', 'MSB - Ngân hàng Hàng Hải'), ('OCB', 'OCB - Ngân hàng Phương Đông'), ('SHB', 'SHB - Sài Gòn Hà Nội')], default='MBBank', max_length=50, verbose_name='Ngân hàng nhận'),
        ),
    ]
