from decimal import Decimal
from datetime import date, time

faculties_data = [
    {
        "code": "CNTT",
        "name": "Khoa Công nghệ thông tin",
        "majors": [
            {"code": "7480101", "name": "Khoa học máy tính"},
            {"code": "7480201", "name": "Công nghệ thông tin"},
        ],
    },
    {
        "code": "XD",
        "name": "Khoa Xây dựng",
        "majors": [
            {"code": "7510102", "name": "Công nghệ kỹ thuật công trình xây dựng"},
            {"code": "7510103", "name": "Quản lý xây dựng"},
        ],
    },
]

cohorts_data = [
    {"code": "K23", "enrollment_year": 2023},
    {"code": "K24", "enrollment_year": 2024},
    {"code": "K25", "enrollment_year": 2025},
    {"code": "K26", "enrollment_year": 2026},
]

grade_conversion_rules_data = [
    {
        "min": Decimal("9.0"),
        "max": Decimal("10.0"),
        "letter": "A+",
        "score4": Decimal("4.0"),
        "classification": "PASS",
    },
    {
        "min": Decimal("8.5"),
        "max": Decimal("8.9"),
        "letter": "A",
        "score4": Decimal("4.0"),
        "classification": "PASS",
    },
    {
        "min": Decimal("8.0"),
        "max": Decimal("8.4"),
        "letter": "B+",
        "score4": Decimal("3.5"),
        "classification": "PASS",
    },
    {
        "min": Decimal("7.0"),
        "max": Decimal("7.9"),
        "letter": "B",
        "score4": Decimal("3.0"),
        "classification": "PASS",
    },
    {
        "min": Decimal("6.5"),
        "max": Decimal("6.9"),
        "letter": "C+",
        "score4": Decimal("2.5"),
        "classification": "PASS",
    },
    {
        "min": Decimal("5.5"),
        "max": Decimal("6.4"),
        "letter": "C",
        "score4": Decimal("2.0"),
        "classification": "PASS",
    },
    {
        "min": Decimal("5.0"),
        "max": Decimal("5.4"),
        "letter": "D+",
        "score4": Decimal("1.5"),
        "classification": "PASS",
    },
    {
        "min": Decimal("4.0"),
        "max": Decimal("4.9"),
        "letter": "D",
        "score4": Decimal("1.0"),
        "classification": "PASS",
    },
    {
        "min": Decimal("0.0"),
        "max": Decimal("3.9"),
        "letter": "F",
        "score4": Decimal("0.0"),
        "classification": "FAIL",
    },
]

semesters_data = [
    {"code": "20231", "start_date": date(2023, 9, 5), "end_date": date(2024, 1, 15)},
    {"code": "20232", "start_date": date(2024, 2, 15), "end_date": date(2024, 6, 15)},
    {"code": "20233", "start_date": date(2024, 6, 25), "end_date": date(2024, 8, 15)},
    {"code": "20241", "start_date": date(2024, 9, 5), "end_date": date(2025, 1, 15)},
    {"code": "20242", "start_date": date(2025, 2, 15), "end_date": date(2025, 6, 15)},
    {"code": "20243", "start_date": date(2025, 6, 25), "end_date": date(2025, 8, 15)},
    {"code": "20251", "start_date": date(2025, 9, 5), "end_date": date(2026, 1, 15)},
    {"code": "20252", "start_date": date(2026, 2, 15), "end_date": date(2026, 6, 15)},
    {"code": "20253", "start_date": date(2026, 6, 25), "end_date": date(2026, 8, 15)},
    {"code": "20261", "start_date": date(2026, 9, 5), "end_date": date(2027, 1, 15)},
    {"code": "20262", "start_date": date(2027, 2, 15), "end_date": date(2027, 6, 15)},
    {"code": "20263", "start_date": date(2027, 6, 25), "end_date": date(2027, 8, 15)},
    {"code": "20271", "start_date": date(2027, 9, 5), "end_date": date(2028, 1, 15)},
    {"code": "20272", "start_date": date(2028, 2, 15), "end_date": date(2028, 6, 15)},
    {"code": "20273", "start_date": date(2028, 6, 25), "end_date": date(2028, 8, 15)},
]

subjects_data = [
    # CNTT
    {
        "code": "IT001",
        "name": "Nhập môn lập trình",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "IT011",
        "name": "Toán rời rạc",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "IT004",
        "name": "Mạng máy tính",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "IT012",
        "name": "Kiến trúc máy tính",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "IT002",
        "name": "Cấu trúc dữ liệu và giải thuật",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": ["IT001"],
    },
    {
        "code": "IT013",
        "name": "Cơ sở dữ liệu",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "IT005",
        "name": "Hệ điều hành",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": ["IT012"],
    },
    {
        "code": "IT014",
        "name": "Phân tích thiết kế hệ thống",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "IT015",
        "name": "Lập trình hướng đối tượng",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "IT016",
        "name": "Mật mã học cơ sở",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "CS003",
        "name": "Đồ họa máy tính",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "CS011",
        "name": "Thị giác máy tính",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "CS001",
        "name": "Trí tuệ nhân tạo",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": ["IT002"],
    },
    {
        "code": "CS012",
        "name": "Xử lý ảnh số",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "CS002",
        "name": "Học máy",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": ["CS001"],
    },
    {
        "code": "CS013",
        "name": "Xử lý ngôn ngữ tự nhiên",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "CS014",
        "name": "Chuyên đề Khoa học máy tính",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "CS099",
        "name": "Đồ án tốt nghiệp KHMT",
        "credits": 6,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "SE001",
        "name": "Công nghệ phần mềm",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "SE011",
        "name": "Kiểm thử phần mềm",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "SE002",
        "name": "Phát triển ứng dụng Web",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": ["IT013"],
    },
    {
        "code": "SE012",
        "name": "Thiết kế giao diện UI/UX",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "SE015",
        "name": "Thiết kế trải nghiệm người dùng",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "SE003",
        "name": "Phát triển ứng dụng Di động",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": ["IT001"],
    },
    {
        "code": "SE013",
        "name": "Kiến trúc phần mềm",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "SE014",
        "name": "Chuyên đề Công nghệ thông tin",
        "credits": 3,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    {
        "code": "SE099",
        "name": "Đồ án tốt nghiệp CNTT",
        "credits": 6,
        "faculty_code": "CNTT",
        "prereqs": [],
    },
    # XD
    {
        "code": "CE001",
        "name": "Cơ học cơ sở",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CE011",
        "name": "Hình họa - Vẽ kỹ thuật",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CE003",
        "name": "Vật liệu xây dựng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CE012",
        "name": "Kiến trúc dân dụng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CE002",
        "name": "Sức bền vật liệu",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": ["CE001"],
    },
    {
        "code": "CE013",
        "name": "Thủy lực cơ sở",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CE004",
        "name": "Trắc địa",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CE014",
        "name": "Cơ học kết cấu",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CE005",
        "name": "Cơ học đất",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": ["CE002"],
    },
    {
        "code": "CE015",
        "name": "Máy xây dựng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CT001",
        "name": "Kỹ thuật thi công",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CT011",
        "name": "Kết cấu thép",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CT002",
        "name": "Kết cấu bê tông cốt thép",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": ["CE002"],
    },
    {
        "code": "CT012",
        "name": "Động đất và chống động đất",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CT003",
        "name": "Nền móng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": ["CE005"],
    },
    {
        "code": "CT013",
        "name": "Thi công cầu đường",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CT014",
        "name": "Chuyên đề Kỹ thuật Xây dựng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CT099",
        "name": "Đồ án tốt nghiệp KTXD",
        "credits": 6,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CM001",
        "name": "Kinh tế xây dựng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CM011",
        "name": "Kế toán xây dựng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CM004",
        "name": "Luật xây dựng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CM012",
        "name": "Định giá xây dựng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CM002",
        "name": "Lập dự toán",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": ["CM001"],
    },
    {
        "code": "CM013",
        "name": "Quản lý chất lượng dự án",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CM014",
        "name": "Chuyên đề Quản lý Xây dựng",
        "credits": 3,
        "faculty_code": "XD",
        "prereqs": [],
    },
    {
        "code": "CM099",
        "name": "Đồ án tốt nghiệp QLXD",
        "credits": 6,
        "faculty_code": "XD",
        "prereqs": [],
    },
]
